# -*- coding: utf-8 -*-
"""finalPRP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106zOWDsZOyvmlinsOfn11KasRfS0vuhe

## FINAL
"""

import cv2
import numpy as np
import gradio as gr
import joblib

model = joblib.load('fruit_classifier.pkl')

dataset_path = "train"
categories = {"Apple" : 0,"Banana" : 1,"Mango" : 2,"Strawberry" : 3,"Grape" : 4}
labels = ["Apple", "Banana", "Mango", "Strawberry", "Grape"]
img_size = 64

def classify(img):
    if img is None:
        return "No image uploaded"

    img_bgr = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)


    img_resized = cv2.resize(img_bgr, (64, 64))

    img_flattened = img_resized.flatten().reshape(1, -1)





    prediction_index = model.predict(img_flattened)[0]


    fruit_name = labels[prediction_index]

    return f"Result: {fruit_name}"

check = gr.Interface(
    fn = classify,
    inputs = gr.Image(),
    outputs = "text",
    title = "Fruits Recognition",
    description=f"Upload an image of: {','.join(categories.keys())}"
)

if __name__ == "__main__":
  check.launch()