# -*- coding: utf-8 -*-
"""PRP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhjUIGFLrRn5MjXPxOerNfx0cLRBAi7b
"""

import os
import cv2
import numpy as np
import gradio as gr
import random
from sklearn.ensemble import RandomForestClassifier
import time

dataset_path = "train"
categories = {"Apple" : 0,"Banana" : 1,"Mango" : 2,"Strawberry" : 3,"Grape" : 4}
labels = {k : v for v,k in categories.items()}
img_size = 64

def load():
    X, y = [], []
    for fruit, label in categories.items():
        path = os.path.join(dataset_path, fruit)

        files = os.listdir(path)
        random.shuffle(files)
        files = files[:800]

        for img_name in files:
            img_path = os.path.join(path, img_name)
            img = cv2.imread(img_path)
            if img is not None:
                img = cv2.resize(img, (64, 64))

                X.append(img.flatten())
                y.append(label)
    return np.array(X), np.array(y)

X_train, y_train = load()

if len(X_train) > 0 :
  print(f"Training LinearSVM on {len(X_train)} images.....")
  model = RandomForestClassifier(n_estimators=100, random_state=42)
  model.fit(X_train,y_train)
  print("Model trained successfully")
else :
 print("Error: No training data found. Check your folder structure")

import joblib

joblib.dump(model, 'fruit_classifier.pkl')
print("Model saved successfully as 'fruit_classifier.pkl'!")



from sklearn.metrics import accuracy_score
y_pred = model.predict(X_train)
print(f"Training Accuracy: {accuracy_score(y_train, y_pred)*100:.2f}%")